# test-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: medicure-test
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: medicure
  template:
    metadata:
      labels:
        app: medicure
    spec:
      nodeSelector:
        env: test
      containers:
      - name: medicure
        image: yourdockerhub/medicure:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: medicure-test-svc
  namespace: test
spec:
  selector:
    app: medicure
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP
